"""add purchase_date to animals

Revision ID: 60bc8a7819f0
Revises: fc1523bf06de
Create Date: 2026-05-01 00:55:32.518901

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bc8a7819f0'
down_revision: Union[str, None] = 'fc1523bf06de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'purchase_date')
    # ### end Alembic commands ###
