"""add device_push_tokens and price_alerts

Revision ID: 82721790efcc
Revises: 36bd7d3813f1
Create Date: 2026-04-27 22:58:46.030383

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82721790efcc'
down_revision: Union[str, None] = '36bd7d3813f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
