"""extend user profile with farmer fields

Revision ID: a6bc51f80ab9
Revises: 6cdb42e4e4f4
Create Date: 2026-05-03 22:54:29.590440

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bc51f80ab9'
down_revision: Union[str, None] = '6cdb42e4e4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    op.add_column('users', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('animal_types', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified_farmer', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified_farmer')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'animal_types')
    op.drop_column('users', 'years_experience')
    op.drop_column('users', 'region')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
