"""add purchase_price to animals

Revision ID: fc1523bf06de
Revises: 82721790efcc
Create Date: 2026-05-01 00:14:03.793452

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1523bf06de'
down_revision: Union[str, None] = '82721790efcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('purchase_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'purchase_price')
    # ### end Alembic commands ###
